# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(501, 523)
        mainWindow.setMinimumSize(QtCore.QSize(451, 301))
        mainWindow.setTabletTracking(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setToolTip("")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setCenterOnScroll(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_3.addWidget(self.plainTextEdit, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.voteformLayout = QtWidgets.QFormLayout()
        self.voteformLayout.setObjectName("voteformLayout")
        self.add_vote_countLabel = QtWidgets.QLabel(self.centralwidget)
        self.add_vote_countLabel.setToolTip("")
        self.add_vote_countLabel.setObjectName("add_vote_countLabel")
        self.voteformLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.add_vote_countLabel)
        self.add_vote_countSpinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.add_vote_countSpinbox.setMaximum(9999)
        self.add_vote_countSpinbox.setProperty("value", 1)
        self.add_vote_countSpinbox.setObjectName("add_vote_countSpinbox")
        self.voteformLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.add_vote_countSpinbox)
        self.vote_control_countLabel = QtWidgets.QLabel(self.centralwidget)
        self.vote_control_countLabel.setToolTip("")
        self.vote_control_countLabel.setObjectName("vote_control_countLabel")
        self.voteformLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.vote_control_countLabel)
        self.vote_control_countSpinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.vote_control_countSpinbox.setMaximum(9999)
        self.vote_control_countSpinbox.setProperty("value", 2)
        self.vote_control_countSpinbox.setObjectName("vote_control_countSpinbox")
        self.voteformLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.vote_control_countSpinbox)
        self.vote_reply_countLabel = QtWidgets.QLabel(self.centralwidget)
        self.vote_reply_countLabel.setToolTip("")
        self.vote_reply_countLabel.setObjectName("vote_reply_countLabel")
        self.voteformLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.vote_reply_countLabel)
        self.vote_reply_countSpinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.vote_reply_countSpinbox.setMaximum(9999)
        self.vote_reply_countSpinbox.setProperty("value", 1)
        self.vote_reply_countSpinbox.setObjectName("vote_reply_countSpinbox")
        self.voteformLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.vote_reply_countSpinbox)
        self.gridLayout_2.addLayout(self.voteformLayout, 0, 0, 1, 1)
        self.choiceverticalLayout = QtWidgets.QVBoxLayout()
        self.choiceverticalLayout.setObjectName("choiceverticalLayout")
        self.voteCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.voteCheckbox.setIconSize(QtCore.QSize(10, 10))
        self.voteCheckbox.setChecked(True)
        self.voteCheckbox.setObjectName("voteCheckbox")
        self.choiceverticalLayout.addWidget(self.voteCheckbox, 0, QtCore.Qt.AlignHCenter)
        self.vote_upCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.vote_upCheckbox.setTabletTracking(False)
        self.vote_upCheckbox.setChecked(True)
        self.vote_upCheckbox.setObjectName("vote_upCheckbox")
        self.choiceverticalLayout.addWidget(self.vote_upCheckbox, 0, QtCore.Qt.AlignHCenter)
        self.vote_replyCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vote_replyCheckbox.sizePolicy().hasHeightForWidth())
        self.vote_replyCheckbox.setSizePolicy(sizePolicy)
        self.vote_replyCheckbox.setChecked(True)
        self.vote_replyCheckbox.setObjectName("vote_replyCheckbox")
        self.choiceverticalLayout.addWidget(self.vote_replyCheckbox, 0, QtCore.Qt.AlignHCenter)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.choiceverticalLayout.addWidget(self.line)
        self.topic_upCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.topic_upCheckbox.setChecked(True)
        self.topic_upCheckbox.setObjectName("topic_upCheckbox")
        self.choiceverticalLayout.addWidget(self.topic_upCheckbox, 0, QtCore.Qt.AlignHCenter)
        self.topic_replyCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.topic_replyCheckbox.setChecked(True)
        self.topic_replyCheckbox.setObjectName("topic_replyCheckbox")
        self.choiceverticalLayout.addWidget(self.topic_replyCheckbox, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.choiceverticalLayout, 0, 2, 1, 1)
        self.topicformLayout = QtWidgets.QFormLayout()
        self.topicformLayout.setObjectName("topicformLayout")
        self.add_topic_countLabel = QtWidgets.QLabel(self.centralwidget)
        self.add_topic_countLabel.setToolTip("")
        self.add_topic_countLabel.setObjectName("add_topic_countLabel")
        self.topicformLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.add_topic_countLabel)
        self.add_topic_countSpinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.add_topic_countSpinbox.setMaximum(9999)
        self.add_topic_countSpinbox.setProperty("value", 1)
        self.add_topic_countSpinbox.setObjectName("add_topic_countSpinbox")
        self.topicformLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.add_topic_countSpinbox)
        self.topic_control_countLabel = QtWidgets.QLabel(self.centralwidget)
        self.topic_control_countLabel.setToolTip("")
        self.topic_control_countLabel.setObjectName("topic_control_countLabel")
        self.topicformLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.topic_control_countLabel)
        self.topic_control_countSpinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.topic_control_countSpinbox.setMaximum(9999)
        self.topic_control_countSpinbox.setProperty("value", 2)
        self.topic_control_countSpinbox.setObjectName("topic_control_countSpinbox")
        self.topicformLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.topic_control_countSpinbox)
        self.topic_reply_countSpinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.topic_reply_countSpinbox.setMaximum(9999)
        self.topic_reply_countSpinbox.setProperty("value", 1)
        self.topic_reply_countSpinbox.setObjectName("topic_reply_countSpinbox")
        self.topicformLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.topic_reply_countSpinbox)
        self.topic_reply_countLabel = QtWidgets.QLabel(self.centralwidget)
        self.topic_reply_countLabel.setToolTip("")
        self.topic_reply_countLabel.setObjectName("topic_reply_countLabel")
        self.topicformLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.topic_reply_countLabel)
        self.gridLayout_2.addLayout(self.topicformLayout, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 2, 0, 1, 2)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setSpacing(4)
        self.formLayout_4.setObjectName("formLayout_4")
        self.tokenLabel = QtWidgets.QLabel(self.centralwidget)
        self.tokenLabel.setToolTip("")
        self.tokenLabel.setWhatsThis("")
        self.tokenLabel.setObjectName("tokenLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tokenLabel)
        self.tokenLineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.tokenLineedit.setText("")
        self.tokenLineedit.setObjectName("tokenLineedit")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tokenLineedit)
        self.urlLabel = QtWidgets.QLabel(self.centralwidget)
        self.urlLabel.setToolTip("")
        self.urlLabel.setWhatsThis("")
        self.urlLabel.setObjectName("urlLabel")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.urlLabel)
        self.waitLabel = QtWidgets.QLabel(self.centralwidget)
        self.waitLabel.setToolTip("")
        self.waitLabel.setObjectName("waitLabel")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.waitLabel)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setDecimals(2)
        self.doubleSpinBox.setMinimum(0.1)
        self.doubleSpinBox.setMaximum(9999.99)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setProperty("value", 3.6)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox)
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setObjectName("loginButton")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.loginButton)
        self.lauchButton = QtWidgets.QPushButton(self.centralwidget)
        self.lauchButton.setObjectName("lauchButton")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.lauchButton)
        self.NotePad = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NotePad.sizePolicy().hasHeightForWidth())
        self.NotePad.setSizePolicy(sizePolicy)
        self.NotePad.setObjectName("NotePad")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.NotePad)
        self.urlLineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.urlLineedit.setObjectName("urlLineedit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.urlLineedit)
        self.gridLayout_3.addLayout(self.formLayout_4, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "易班 EGPA"))
        self.plainTextEdit.setStatusTip(_translate("mainWindow", "程序输出日志，如出错请咨询开发者"))
        self.plainTextEdit.setPlainText(_translate("mainWindow", "Made by Simon Shi\n"
"在左侧使用账号/密码登录，待程序自动填入 Cookies 后，点击启动即可刷EGPA。"))
        self.add_vote_countLabel.setStatusTip(_translate("mainWindow", "发起投票数量，如不需要请改为0关闭自动发起投票"))
        self.add_vote_countLabel.setText(_translate("mainWindow", "发起投票数量"))
        self.add_vote_countSpinbox.setStatusTip(_translate("mainWindow", "发起投票数量，如不需要请改为0关闭自动发起投票"))
        self.vote_control_countLabel.setStatusTip(_translate("mainWindow", "操作控制投票帖子数量，如不需要请改为0关闭操作控制投票帖子"))
        self.vote_control_countLabel.setText(_translate("mainWindow", "投票互动数量"))
        self.vote_control_countSpinbox.setStatusTip(_translate("mainWindow", "操作控制投票帖子数量，如不需要请改为0关闭操作控制投票帖子"))
        self.vote_reply_countLabel.setStatusTip(_translate("mainWindow", "回复投票次数，如不需要请改为0关闭回复投票"))
        self.vote_reply_countLabel.setText(_translate("mainWindow", "回复投票次数"))
        self.vote_reply_countSpinbox.setStatusTip(_translate("mainWindow", "回复投票次数，如不需要请改为0关闭回复投票"))
        self.voteCheckbox.setText(_translate("mainWindow", "开启参与投票"))
        self.vote_upCheckbox.setText(_translate("mainWindow", "开启投票点赞"))
        self.vote_replyCheckbox.setText(_translate("mainWindow", "开启回复投票"))
        self.topic_upCheckbox.setText(_translate("mainWindow", "开启话题点赞"))
        self.topic_replyCheckbox.setText(_translate("mainWindow", "开启回复话题"))
        self.add_topic_countLabel.setStatusTip(_translate("mainWindow", "发起话题数量，如不需要请改为0关闭自动发起话题"))
        self.add_topic_countLabel.setText(_translate("mainWindow", "发起话题数量"))
        self.add_topic_countSpinbox.setStatusTip(_translate("mainWindow", "发起话题数量，如不需要请改为0关闭自动发起话题"))
        self.topic_control_countLabel.setStatusTip(_translate("mainWindow", "操作控制话题帖子数量，如不需要请改为0关闭操作控制话题帖子"))
        self.topic_control_countLabel.setText(_translate("mainWindow", "话题互动数量"))
        self.topic_control_countSpinbox.setStatusTip(_translate("mainWindow", "操作控制话题帖子数量，如不需要请改为0关闭操作控制话题帖子"))
        self.topic_reply_countSpinbox.setStatusTip(_translate("mainWindow", "回复话题次数，如不需要请改为0关闭回复话题"))
        self.topic_reply_countLabel.setStatusTip(_translate("mainWindow", "回复话题次数，如不需要请改为0关闭回复话题"))
        self.topic_reply_countLabel.setText(_translate("mainWindow", "回复话题次数"))
        self.tokenLabel.setStatusTip(_translate("mainWindow", "Cookies是易班账号密码验证的短期临时替代方式，重新登录将重置Cookies"))
        self.tokenLabel.setText(_translate("mainWindow", "Cookies"))
        self.tokenLineedit.setStatusTip(_translate("mainWindow", "Cookies是易班账号密码验证的短期临时替代方式，重新登录将重置Cookies"))
        self.urlLabel.setStatusTip(_translate("mainWindow", "填入文本内容生成的链接"))
        self.urlLabel.setText(_translate("mainWindow", "文本生成链接"))
        self.waitLabel.setStatusTip(_translate("mainWindow", "每个操作之间的间隔，填入浮点数"))
        self.waitLabel.setText(_translate("mainWindow", "等待时间间隔"))
        self.doubleSpinBox.setStatusTip(_translate("mainWindow", "每个操作之间的间隔，填入浮点数"))
        self.loginButton.setText(_translate("mainWindow", "账号/密码登录"))
        self.lauchButton.setText(_translate("mainWindow", "启动"))
        self.NotePad.setPlainText(_translate("mainWindow", "这里可以填写备忘录"))
        self.urlLineedit.setStatusTip(_translate("mainWindow", "填入文本内容生成的链接"))
        self.urlLineedit.setText(_translate("mainWindow", "https://v1.hitokoto.cn/?encode=text"))
